force-app/main/default/objects/Lead/fields/WSCountry__c.field-meta.xml
<CustomField>
    <fullName>WSCountry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the WSCountry</description>
    <label>WSCountry</label>
    <referenceTo>WSCountry__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WSCountry__c/WSCountry__c.object-meta.xml
<CustomObject>
    <description>Countries from https://restcountries.com/v3.1/all</description>
    <label>WSCountry</label>
    <nameField>
        <label>WSCountry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WSCountries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WSCountry__c/fields/Capital__c.field-meta.xml
<CustomField>
    <fullName>Capital__c</fullName>
    <description>Capital City</description>
    <label>Capital</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WSCountry__c/fields/ISO2__c.field-meta.xml
<CustomField>
    <fullName>ISO2__c</fullName>
    <description>Country ISO code 2</description>
    <label>ISO2</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WSCountry__c/fields/ISO3__c.field-meta.xml
<CustomField>
    <fullName>ISO3__c</fullName>
    <description>Country ISO code 3</description>
    <label>ISO3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WSCountry__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Country Region</description>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WSCountry__c/fields/Subregion__c.field-meta.xml
<CustomField>
    <fullName>Subregion__c</fullName>
    <description>Country subregion</description>
    <label>Subregion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadUpdateWSCountryBatchTest.cls
//test class for LeadUpdateWSCountryBatch
//test coverage: 100%

@isTest
public class LeadUpdateWSCountryBatchTest {
    @isTest
    static void testLeadUpdateWSCountryBatch() {
        WSCountry__c wsCountry1 = new WSCountry__C(Name = 'France', Capital__c = 'Paris', ISO2__c = 'FR', ISO3__c = 'FRA', Region__c = 'Europe', Subregion__c = 'Western Europe');
        insert wsCountry1;
    	Lead ld = new Lead(LastName='Lead1Test', company = 'test lead company', status = 'Open - Not Contacted', country = 'France');
        insert ld;
		Test.StartTest();
			Id batchJobId = Database.executeBatch(new LeadUpdateWSCountryBatch(), 10);
    	Test.stopTest();
    }
}